language: csharp
mono: latest
dotnet: 3.1.200

install:
# - choco install dotnetcore-sdk
  - msbuild /t:Restore
script:
 - msbuild ./MintPlayer.UpdateDialog/MintPlayer.UpdateDialog.csproj /t:Build /p:Configuration=Release
