os: windows
language: csharp
mono: none

install:
 - choco install dotnetcore-sdk
 - dotnet restore
script:
 - dotnet build ./MintPlayer.UpdateDialog/MintPlayer.UpdateDialog.csproj --configuration Release
