os: windows
language: csharp
mono: latest

install:
# - choco install dotnetcore-sdk
  - msbuild /t:Restore
script:
 - msbuild ./MintPlayer.UpdateDialog/MintPlayer.UpdateDialog.csproj /t:Build /p:Configuration=Release
